name: Lint Checking

on:
  repository_dispatch:
    types: [trigger-lint-check]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable